enable_ansible_debug: false # set value to true for verbose output from ansible

# format: "http://<jumphost_ip>:40001"
nsx_image_webserver: "http://192.168.110.11:40001"

# NSX general network settings
mgmt_portgroup: 'ESXi-RegionA01-vDS-COMP'
dns_server: 192.168.110.10
dns_domain: corp.local.io
ntp_servers: time.vmware.com
default_gateway: 192.168.110.1
netmask: 255.255.255.0

# NSX manager cluster configs
nsx_manager_ips: 192.168.110.33,192.168.110.34,192.168.110.35 # 3 node cluster is recommended. 1 is minimum, 3 is max
nsx_manager_username: admin
nsx_manager_password: Admin!23Admin
nsx_manager_hostname_prefix: "nsxt-mgr" # Generated hostname: nsxt-mgr-1.corp.local.io, will be FQDN
nsx_manager_root_pwd: Admin!23Admin # Min 12 chars, upper, lower, number, special digit
nsx_manager_cli_pwd: Admin!23Admin
nsx_manager_deployment_size: small # Recommended for real bare-bones demo, smallest setup
nsx_manager_deployment_ip_prefix_length: 23
nsx_manager_ssh_enabled: true
vcenter_ip: 192.168.110.22
vcenter_username: administrator@corp.local
vcenter_password: "VMware1!"
vcenter_datacenter: RegionA01
vcenter_cluster: RegionA01-MGMT # management cluster
vcenter_datastore: iscsi
resource_reservation_off: true

# Compute manager credentials should be the same as above vCenter's if
# controllers and edges are to be on the same vCenter
compute_manager_username: "Administrator@vsphere.local"
compute_manager_password: "VMware1!"
# compute manager for the compute cluster (2nd vCenter)
compute_manager_2_vcenter_ip: "null"
compute_manager_2_username: "null"
compute_manager_2_password: "null"

esxi_uplink_profile_vlan: 0 # For internal overlay connection used by Esxi hosts, usually trasnport VLAN ID

# Virtual Tunnel Endpoint network ip pool
vtep_ip_pool_cidr: 192.168.213.0/24
vtep_ip_pool_gateway: 192.168.213.1
vtep_ip_pool_start: 192.168.213.10
vtep_ip_pool_end: 192.168.213.200

# Tier 0 router
tier0_router_name: DefaultT0Router
tier0_uplink_port_ip: 192.168.100.4
tier0_uplink_port_subnet: 24
tier0_uplink_next_hop_ip: 192.168.100.1
tier0_uplink_port_ip_2: 192.168.100.5
tier0_ha_vip: 192.168.100.3

## Edge nodes
edge_ips: 192.168.110.37,192.168.110.38    #comma separated based in number of required edges
edge_default_gateway: 192.168.110.1
edge_ip_prefix_length: 24
edge_hostname_prefix: nsx-t-edge
edge_transport_node_prefix: edge-transp-node
edge_cli_password: "VMware1!"
edge_root_password: "VMware1!"
edge_deployment_size: "large" #Large recommended for PKS deployments
edge_uplink_profile_vlan: 0 # For outbound uplink connection used by Edge, usually keep as 0
vc_datacenter_for_edge: RegionA01
vc_cluster_for_edge: RegionA01-MGMT
vc_datastore_for_edge: iscsi
vc_uplink_network_for_edge: "ESXi-RegionA01-vDS-COMP"
vc_overlay_network_for_edge: "VM-RegionA01-vDS-COMP"
vc_management_network_for_edge: "ESXi-RegionA01-vDS-COMP"

# Default Tier 0 router
tier0_router_name: SharedT0Router
tier0_uplink_port_ip: 192.168.100.4
tier0_uplink_port_subnet: 24
tier0_uplink_next_hop_ip: 192.168.100.1
tier0_uplink_port_ip_2: 192.168.100.5
tier0_ha_vip: 192.168.100.3
vlan_logical_switch_name: shared_vlan_ls
inter_tier0_network_ip: 50.0.0.1
inter_tier0_network_ip_2: 50.0.0.2
is_tanent: false
bgp_as_number: 65200

# Tenant edge clusters (one needed for each tenant)
tenant_edge_clusters:

- edge_cluster_name: Edge-Cls-Tenant1
  edge_ips: 192.168.110.47,192.168.110.48  #comma separated based in number of required edges
  edge_default_gateway: 192.168.110.1
  edge_ip_prefix_length: 24
  edge_hostname_prefix: tenant1-edge
  edge_transport_node_prefix: tenant1-edge-transp-node
  edge_cli_password: "VMware1!"
  edge_root_password: "VMware1!"
  edge_deployment_size: "large"   #Large recommended for PKS deployments
  edge_uplink_profile_vlan: 10
  edge_uplink_profile_name: tenant1_uplink_prof
  vc_datacenter_for_edge: RegionA01
  vc_cluster_for_edge: RegionA01-edge-cls2
  vc_datastore_for_edge: edge-datastore
  vc_uplink_network_for_edge: Tanent1-T0-uplink
  vc_overlay_network_for_edge: Tanent1-T0-Overlay
  vc_management_network_for_edge: "ESXi-RegionA01-vDS-COMP"

- edge_cluster_name: Edge-Cls-Tenant2
  edge_ips: 192.168.110.57,192.168.110.58  #comma separated based in number of required edges
  edge_default_gateway: 192.168.110.1
  edge_ip_prefix_length: 24
  edge_hostname_prefix: tenant2-edge
  edge_transport_node_prefix: tenant2-edge-transp-node
  edge_cli_password: "VMware1!"
  edge_root_password: "VMware1!"
  edge_deployment_size: "large"   #Large recommended for PKS deployments
  edge_uplink_profile_vlan: 20
  edge_uplink_profile_name: tenant2_uplink_prof
  vc_datacenter_for_edge: RegionA01
  vc_cluster_for_edge: RegionA01-edge-cls3
  vc_datastore_for_edge: edge-datastore
  vc_uplink_network_for_edge: Tanent1-T0-uplink
  vc_overlay_network_for_edge: Tanent1-T0-Overlay
  vc_management_network_for_edge: "ESXi-RegionA01-vDS-COMP"

# Tenant Tier 0 routers (one needed for each tenant)
tenant_t0s:

- tier0_router_name: Tenant1T0Router
  tier0_uplink_port_ip: 192.168.101.4
  tier0_uplink_port_subnet: 24
  tier0_uplink_next_hop_ip: 192.168.101.1
  tier0_uplink_port_ip_2: 192.168.101.5
  tier0_ha_vip: 192.168.101.3
  edge_cluster_name: Edge-Cls-Tenant1 #refer to the edge cluster name set for this T0
  vlan_logical_switch_name: tenant1_vlan_ls
  inter_tier0_network_ip: 50.0.0.3
  inter_tier0_network_ip_2: 50.0.0.4
  is_tanent: true
  bgp_as_number: 65201

- tier0_router_name: Tenant2T0Router
  tier0_uplink_port_ip: 192.168.102.4
  tier0_uplink_port_subnet: 24
  tier0_uplink_next_hop_ip: 192.168.102.1
  tier0_uplink_port_ip_2: 192.168.102.5
  tier0_ha_vip: 192.168.102.3
  edge_cluster_name: Edge-Cls-Tenant2 #refer to the edge cluster name set for this T0
  vlan_logical_switch_name: tenant2_vlan_ls
  inter_tier0_network_ip: 50.0.0.5
  inter_tier0_network_ip_2: 50.0.0.6
  is_tanent: true
  bgp_as_number: 65202

# Inter-T0 Logical network
inter_t0_logical_switch_name: inter-t0-logical-switch
inter_t0_transport_zone_name: inter-t0-tz
inter_t0_vlan: 0
inter_t0_cidr: 50.0.0.0/24

## ESX hosts
#Intsll vSphere clusters automatically
clusters_to_install_nsx: RegionA01-MGMT,RegionA01-K8s    #Comma seprated
per_cluster_vlans: 0,0  #Comma seprated, order of VLANs applied same as order of clusters

esx_ips: "" # additional esx hosts, if any, to be individually installed
esx_os_version: "6.5.0"
esx_root_password: "ca$hc0w"
esx_hostname_prefix: "esx-host"
esx_available_vmnic: "vmnic1" # comma separated physical NICs, applies to both cluster installation or ESXi installation

## BGP related configurations
nsx_t_ip_prefix_spec: |
  ip_prefix_lists:
  - display_name: "shared-t0-prefixes"
    t0_router: SharedT0Router     # Name as specified in the Default Tier 0 router section above
    prefixes:
    - action: "PERMIT"
      network: 30.0.0.0/24        # PKS management network
    - action: "PERMIT"
      network: 192.168.110.0/24   # NSX management network
    - action: "DENY"
      network: 0.0.0.0/24

  - display_name: "tenant1-t0-prefixes"
    t0_router: Tenant1T0Router     # Name as specified in the tenant_t0s section above
    prefixes:
    - action: "PERMIT"
      network: 30.0.128.0/17       # K8S Node network
      ge: 24
      le: 24
    # TODO!! An unknown permit network here
    - action: "DENY"
      network: 0.0.0.0/24

  - display_name: "tenant2-t0-prefixes"
      t0_router: Tenant2T0Router     # Name as specified in the tenant_t0s section above
      prefixes:
      # TODO!! Check this is k8s node network for tenant 2
      - action: "PERMIT"
        network: 40.0.128.0/17       # K8S Node network
        ge: 24
        le: 24
      # TODO!! An unknown permit network here
      - action: "DENY"
        network: 0.0.0.0/24

nsx_t_t0_bgp_spec: |
  bgp_configs:
  - display_name: "shared-t0-bgp"
    t0_router: SharedT0Router
    neighbors:
    - type: "t0_router"
      t0_router_name: Tenant1T0Router
      out_filter_ip_prefix: shared-t0-prefixes
    - type: "t0_router"
      t0_router_name: Tenant2T0Router
      out_filter_ip_prefix: shared-t0-prefixes  # Refer to the ip prefix created above
    redistribution_configs:
    - rule_name: shared-criteria
      sources: [T0_STATIC, T0_CONNECTED, T1_STATIC]

  - display_name: "tenant1-t0-bgp"
    t0_router: Tenant1T0Router
    neighbors:
    - type: "t0_router"
      t0_router_name: SharedT0Router
      out_filter_ip_prefix: tenant1-t0-prefixes  # Refer to the ip prefix created above
    redistribution_configs:
    - rule_name: tenant1-criteria
      sources: [T0_CONNECTED, T1_STATIC, T0_NAT]

  - display_name: "tenant2-t0-bgp"
    t0_router: Tenant2T0Router
    neighbors:
    - type: "t0_router"
      t0_router_name: SharedT0Router
      out_filter_ip_prefix: tenant2-t0-prefixes  # Refer to the ip prefix created above
    redistribution_configs:
    - rule_name: tenant2-criteria
      sources: [T0_CONNECTED, T1_STATIC, T0_NAT]



nsx_t_t1router_logical_switches_spec: |
  t1_routers:
  # Add additional T1 Routers or collapse switches into same T1 Router as needed
  # Remove unneeded T1 routers
- name: T1-Router-PAS-Infra
    switches:
    - name: PAS-Infra
      logical_switch_gw: 192.168.10.1 # Last octet should be 1 rather than 0
      subnet_mask: 24

  - name: T1-Router-PAS-ERT
    switches:
    - name: PAS-ERT
      logical_switch_gw: 192.168.20.1 # Last octet should be 1 rather than 0
      subnet_mask: 24
    edge_cluster: true

  - name: T1-Router-PAS-Services
    switches:
    - name: PAS-Services
      logical_switch_gw: 192.168.30.1 # Last octet should be 1 rather than 0
      subnet_mask: 24


nsx_t_ha_switching_profile_spec: |
  ha_switching_profiles:
  - name: HASwitchingProfile


nsx_t_container_ip_block_spec: |
  container_ip_blocks:
  - name: PAS-container-ip-block
    cidr: 10.4.0.0/16


nsx_t_external_ip_pool_spec: |
  external_ip_pools:
  - name: snat-vip-pool-for-pas
    cidr: 10.208.40.0/24
    start: 10.208.40.10 # Should not include gateway
    end: 10.208.40.200  # Should not include gateway

  - name: tep-ip-pool2
    cidr: 192.168.220.0/24
    start: 192.168.220.10
    end: 192.168.220.200


# Specify NAT rules
nsx_t_nat_rules_spec: |
  nat_rules:
  # Sample entry for allowing inbound to PAS Ops manager
  - t0_router: DefaultT0Router
    nat_type: dnat
    destination_network: 10.208.40.2   # External IP address for PAS opsmanager
    translated_network: 192.168.10.2     # Internal IP of PAS Ops manager
    rule_priority: 1024                  # Higher priority

  # Sample entry for allowing outbound from PAS Ops Mgr to external
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.10.2         # Internal IP of PAS opsmanager
    translated_network: 10.208.40.2      # External IP address for PAS opsmanager
    rule_priority: 1024                  # Higher priority

  # Sample entry for PAS Infra network SNAT
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.10.0/24      # PAS Infra network cidr
    translated_network: 10.208.40.3      # SNAT External Address for PAS networks
    rule_priority: 8000                  # Lower priority

  # Sample entry for PAS ERT network SNAT
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.20.0/24      # PAS ERT network cidr
    translated_network: 10.208.40.3      # SNAT External Address for PAS networks
    rule_priority: 8000                  # Lower priority

  # Sample entry for PAS Services network SNAT
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.30.0/24      # PAS Services network cidr
    translated_network: 10.208.40.3      # SNAT External Address for PAS networks
    rule_priority: 8001                  # Lower priority


nsx_t_csr_request_spec: |
  csr_request:
    #common_name not required - would use nsx_t_manager_host_name
    org_name: Company            # EDIT
    org_unit: net-integ          # EDIT
    country: US                  # EDIT
    state: CA                    # EDIT
    city: SF                     # EDIT
    key_size: 2048               # Valid values: 2048 or 3072
    algorithm: RSA               # Valid values: RSA or DSA


nsx_t_lbr_spec: |
  loadbalancers:
  # Sample entry for creating LBR for PAS ERT
  - name: PAS-ERT-LBR
    t1_router: T1-Router-PAS-ERT # Should match a previously declared T1 Router
    size: small                  # Allowed sizes: small, medium, large
    virtual_servers:
    - name: goRouter443         # Name that signifies function being exposed
      vip: 10.208.40.4         # Exposed VIP for LBR to listen on
      port: 443
      members:
      - ip: 192.168.20.11       # Internal ip of GoRouter instance 1
        port: 80
      - ip: 192.168.20.12        # Internal ip of GoRouter instance 1
        port: 443
    - name: goRouter80
      vip: 10.208.40.4
      port: 80
      members:
      - ip: 192.168.20.11       # Internal ip of GoRouter instance 1
        port: 80
      - ip: 192.168.20.12       # Internal ip of GoRouter instance 2
        port: 80
    - name: sshProxy            # SSH Proxy exposed to outside
      vip: 10.208.40.5
      port: 2222                # Port 2222 for ssh proxy
      members:
      - ip: 192.168.20.41       # Internal ip of Diego Brain where ssh proxy runs
        port: 2222
