---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: projects.registry.vmware.com/nsxt_gen_pipeline/nsx-t-gen-worker
    tag: ubuntu18-v1

# params:
#   VCENTER_HOST:
#   VCENTER_USR:
#   VCENTER_PWD:


inputs:
  - name: nsx-t-gen-pipeline

run:
  path: nsx-t-gen-pipeline/tasks/uninstall-nsx-t/task.sh

