enable_ansible_debug: false # set value to true for verbose output from ansible

# format: "http://<jumphost_ip>:40001"
nsx_image_webserver: "http://192.168.110.11:40001"

# NSX general network settings
mgmt_portgroup: 'ESXi-RegionA01-vDS-COMP'
dns_server: 192.168.110.10
dns_domain: corp.local.io
ntp_servers: time.vmware.com
default_gateway: 192.168.110.1
netmask: 255.255.255.0

# NSX manager cluster configs
nsx_manager_ips: 192.168.110.33,192.168.110.34,192.168.110.35 # 3 node cluster is recommended. 1 is minimum, 3 is max
nsx_manager_username: admin
nsx_manager_password: Admin!23Admin
nsx_manager_hostname_prefix: "nsxt-mgr" # Generated hostname: nsxt-mgr-1.corp.local.io, will be FQDN
nsx_manager_root_pwd: Admin!23Admin # Min 12 chars, upper, lower, number, special digit
nsx_manager_cli_pwd: Admin!23Admin
nsx_manager_deployment_size: small # Recommended for real bare-bones demo, smallest setup
nsx_manager_deployment_ip_prefix_length: 23
nsx_manager_ssh_enabled: true
vcenter_ip: 192.168.110.22
vcenter_username: administrator@corp.local
vcenter_password: "VMware1!"
vcenter_datacenter: RegionA01
vcenter_cluster: RegionA01-MGMT # management cluster
vcenter_datastore: iscsi
resource_reservation_off: true

# Compute manager credentials should be the same as above vCenter's if
# controllers and edges are to be on the same vCenter
compute_manager_username: "Administrator@vsphere.local"
compute_manager_password: "VMware1!"
# compute manager for the compute cluster (2nd vCenter)
compute_manager_2_vcenter_ip: "null"
compute_manager_2_username: "null"
compute_manager_2_password: "null"

edge_uplink_profile_vlan: 0 # For outbound uplink connection used by Edge, usually keep as 0
esxi_uplink_profile_vlan: 0 # For internal overlay connection used by Esxi hosts, usually trasnport VLAN ID

# Virtual Tunnel Endpoint network ip pool
vtep_ip_pool_cidr: 192.168.213.0/24
vtep_ip_pool_gateway: 192.168.213.1
vtep_ip_pool_start: 192.168.213.10
vtep_ip_pool_end: 192.168.213.200

# Tier 0 router
tier0_router_name: DefaultT0Router
tier0_uplink_port_ip: 192.168.100.4
tier0_uplink_port_subnet: 24
tier0_uplink_next_hop_ip: 192.168.100.1
tier0_uplink_port_ip_2: 192.168.100.5
tier0_ha_vip: 192.168.100.3

## Edge nodes
edge_ips: 192.168.110.37,192.168.110.38    #comma separated based in number of required edges
edge_default_gateway: 192.168.110.1
edge_ip_prefix_length: 24
edge_hostname_prefix: nsx-t-edge
edge_transport_node_prefix: edge-transp-node
edge_cli_password: "VMware1!"
edge_root_password: "VMware1!"
edge_deployment_size: "large" #Large recommended for PKS deployments
vc_datacenter_for_edge: RegionA01
vc_cluster_for_edge: RegionA01-MGMT
vc_datastore_for_edge: iscsi
vc_uplink_network_for_edge: "ESXi-RegionA01-vDS-COMP"
vc_overlay_network_for_edge: "VM-RegionA01-vDS-COMP"
vc_management_network_for_edge: "ESXi-RegionA01-vDS-COMP"

## ESX hosts
#Intsll vSphere clusters automatically
clusters_to_install_nsx: RegionA01-MGMT,RegionA01-K8s    #Comma seprated
per_cluster_vlans: 0,0  #Comma seprated, order of VLANs applied same as order of clusters

esx_ips: "" # additional esx hosts, if any, to be individually installed
esx_os_version: "6.5.0"
esx_root_password: "ca$hc0w"
esx_hostname_prefix: "esx-host"

esx_available_vmnic: "vmnic1" # comma separated physical NICs, applies to both cluster installation or ESXi installation

nsx_t_t1router_logical_switches_spec: |
  t1_routers:
  # Add additional T1 Routers or collapse switches into same T1 Router as needed
  - name: T1-Router-PKS-Infra
    switches:
    - name: PKS-Infra
      logical_switch_gw: 192.168.50.1 # Last octet should be 1 rather than 0
      subnet_mask: 24

  - name: T1Router-PKS-Services
    switches:
    - name: PKS-Services
      logical_switch_gw: 192.168.60.1 # Last octet should be 1 rather than 0
      subnet_mask: 24


nsx_t_container_ip_block_spec: |
  container_ip_blocks:
  - name: PKS-node-ip-block
    cidr: 11.4.0.0/16

  - name: PKS-pod-ip-block
    cidr: 12.4.0.0/16


nsx_t_external_ip_pool_spec: |
  external_ip_pools:

  - name: snat-vip-pool-for-pks
    cidr: 10.208.50.0/24
    start: 10.208.50.10 # Should not include gateway
    end: 10.208.50.200  # Should not include gateway

  - name: tep-ip-pool2
    cidr: 192.168.220.0/24
    start: 192.168.220.10
    end: 192.168.220.200


nsx_t_nat_rules_spec: |
  nat_rules:
  # Sample entry for  PKS-Infra network
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.50.0/24      # PKS Infra network cidr
    translated_network: 10.208.50.3      # SNAT External Address for PKS networks
    rule_priority: 8001                  # Lower priority

  # Sample entry for PKS-Services network
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.60.0/24      # PKS Clusters network cidr
    translated_network: 10.208.50.3      # SNAT External Address for PKS networks
    rule_priority: 8001                  # Lower priority

  # Sample entry for allowing inbound to PKS Ops manager
  - t0_router: DefaultT0Router
    nat_type: dnat
    destination_network: 10.208.50.2     # External IP address for PKS opsmanager
    translated_network: 192.168.50.2     # Internal IP of PKS Ops manager
    rule_priority: 1024                  # Higher priority

  # Sample entry for allowing outbound from PKS Ops Mgr to external
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.50.2        # Internal IP of PAS opsmanager
    translated_network: 10.208.50.2      # External IP address for PAS opsmanager
    rule_priority: 1024                  # Higher priority

  # Sample entry for allowing inbound to PKS Controller
  - t0_router: DefaultT0Router
    nat_type: dnat
    destination_network: 10.208.50.4     # External IP address for PKS opsmanager
    translated_network: 192.168.50.11     # Internal IP of PKS Ops Controller
    rule_priority: 1024                  # Higher priority

  # Sample entry for allowing outbound from PKS Controller to external
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 192.168.50.4        # Internal IP of PKS controller
    translated_network: 10.208.50.4      # External IP address for PKS controller
    rule_priority: 1024                  # Higher priority


nsx_t_csr_request_spec: |
  csr_request:
    #common_name not required - would use nsx_t_manager_host_name
    org_name: Company            # EDIT
    org_unit: net-integ          # EDIT
    country: US                  # EDIT
    state: CA                    # EDIT
    city: SF                     # EDIT
    key_size: 2048               # Valid values: 2048 or 3072
    algorithm: RSA               # Valid values: RSA or DSA


nsx_t_lbr_spec: |
  loadbalancers: